import { Expense } from "@/app/types/expense";

export const mockExpenses: Expense[] = [
  {
    id: "1",
    title: "Lunch at restaurant",
    category: "Food",
    amount: 15.5,
    date: new Date(2025, 11, 4),
    description: "Meal with colleagues",
  },
  {
    id: "2",
    title: "Bus fare",
    category: "Transport",
    amount: 1.6,
    date: new Date(2025, 11, 4),
    description: "Commute to work",
  },
  {
    id: "3",
    title: "Medical appointment",
    category: "Health",
    amount: 50.0,
    date: new Date(2025, 11, 3),
    description: "General practitioner",
  },
  {
    id: "4",
    title: "Movie",
    category: "Entertainment",
    amount: 10.5,
    date: new Date(2025, 11, 2),
    description: "Movie ticket",
  },
  {
    id: "5",
    title: "Grocery shopping",
    category: "Food",
    amount: 45.3,
    date: new Date(2025, 11, 1),
    description: "Weekly groceries",
  },
  {
    id: "6",
    title: "Online course",
    category: "Education",
    amount: 29.99,
    date: new Date(2025, 10, 28),
    description: "Advanced Python",
  },
  {
    id: "7",
    title: "Electricity bill",
    category: "Utilities",
    amount: 78.5,
    date: new Date(2025, 10, 25),
    description: "Monthly bill",
  },
  {
    id: "8",
    title: "Book",
    category: "Education",
    amount: 18.99,
    date: new Date(2025, 10, 20),
    description: "Clean Code",
  },
  {
    id: "9",
    title: "Taxi",
    category: "Transport",
    amount: 12.0,
    date: new Date(2025, 10, 18),
    description: "Ride home",
  },
  {
    id: "10",
    title: "Pizza",
    category: "Food",
    amount: 12.5,
    date: new Date(2025, 10, 15),
    description: "Home delivery",
  },
];

export const expenseCategories = {
  Food: { color: "bg-orange-500", icon: "🍕" },
  Transport: { color: "bg-blue-500", icon: "🚗" },
  Health: { color: "bg-red-500", icon: "⚕️" },
  Entertainment: { color: "bg-purple-500", icon: "🎬" },
  Education: { color: "bg-green-500", icon: "📚" },
  Utilities: { color: "bg-yellow-500", icon: "💡" },
  Other: { color: "bg-gray-500", icon: "📌" },
};
