import { Expense } from "@/app/types/expense";

export const mockExpenses: Expense[] = [
  {
    id: "1",
    title: "Almoço no restaurante",
    category: "Alimentação",
    amount: 15.50,
    date: new Date(2025, 11, 4),
    description: "Refeição com colegas de trabalho",
  },
  {
    id: "2",
    title: "Passagem de autocarro",
    category: "Transporte",
    amount: 1.60,
    date: new Date(2025, 11, 4),
    description: "Ida para o trabalho",
  },
  {
    id: "3",
    title: "Consulta médica",
    category: "Saúde",
    amount: 50.00,
    date: new Date(2025, 11, 3),
    description: "Médico geral",
  },
  {
    id: "4",
    title: "Cinema",
    category: "Entretenimento",
    amount: 10.50,
    date: new Date(2025, 11, 2),
    description: "Bilhete de filme",
  },
  {
    id: "5",
    title: "Compras no supermercado",
    category: "Alimentação",
    amount: 45.30,
    date: new Date(2025, 11, 1),
    description: "Compras semanais",
  },
  {
    id: "6",
    title: "Curso online",
    category: "Educação",
    amount: 29.99,
    date: new Date(2025, 10, 28),
    description: "Python avançado",
  },
  {
    id: "7",
    title: "Conta de energia",
    category: "Utilidades",
    amount: 78.50,
    date: new Date(2025, 10, 25),
    description: "Fatura mensal",
  },
  {
    id: "8",
    title: "Livro",
    category: "Educação",
    amount: 18.99,
    date: new Date(2025, 10, 20),
    description: "Clean Code",
  },
  {
    id: "9",
    title: "Táxi",
    category: "Transporte",
    amount: 12.00,
    date: new Date(2025, 10, 18),
    description: "Volta para casa",
  },
  {
    id: "10",
    title: "Pizza",
    category: "Alimentação",
    amount: 12.50,
    date: new Date(2025, 10, 15),
    description: "Entrega em casa",
  },
];

export const expenseCategories = {
  Alimentação: { color: "bg-orange-500", icon: "🍕" },
  Transporte: { color: "bg-blue-500", icon: "🚗" },
  Saúde: { color: "bg-red-500", icon: "⚕️" },
  Entretenimento: { color: "bg-purple-500", icon: "🎬" },
  Educação: { color: "bg-green-500", icon: "📚" },
  Utilidades: { color: "bg-yellow-500", icon: "💡" },
  Outro: { color: "bg-gray-500", icon: "📌" },
};
